apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pii-cleaner.fullname" . }}
  labels:
    {{- include "pii-cleaner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pii-cleaner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pii-cleaner.selectorLabels" . | nindent 8 }}
      {{- if .Values.prometheus.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
      {{- end }}
    spec:
      serviceAccountName: {{ include "pii-cleaner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 40
      containers:
        - name: pii-cleaner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          volumeMounts:
            - name: tenants
              mountPath: /etc/pii-cleaner/tenants.yaml
              subPath: tenants.yaml
              readOnly: true
            - name: audit-key
              mountPath: /etc/pii-cleaner/audit.key
              subPath: audit.key
              readOnly: true
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tenants
          secret:
            secretName: {{ include "pii-cleaner.fullname" . }}-tenants
        - name: audit-key
          secret:
            secretName: {{ include "pii-cleaner.fullname" . }}-audit
        - name: tmp
          emptyDir: {}
