{{- if .Values.tenants }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pii-cleaner.fullname" . }}-tenants
  labels:
    {{- include "pii-cleaner.labels" . | nindent 4 }}
type: Opaque
stringData:
  tenants.yaml: |
{{ .Values.tenants | indent 4 }}
{{- end }}
---
{{- if .Values.auditHmacKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pii-cleaner.fullname" . }}-audit
  labels:
    {{- include "pii-cleaner.labels" . | nindent 4 }}
type: Opaque
stringData:
  audit.key: {{ .Values.auditHmacKey | quote }}
{{- end }}
