{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pii-cleaner.serviceAccountName" . }}
  labels:
    {{- include "pii-cleaner.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
